#spring
spring:
  datasource:
    url: jdbc:p6spy:mysql://service.cf:3307/train?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: HBQ521521cf*
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      max-lifetime: 500000
  jackson:   #时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis: # Redis服务器地址
    host: service.cf
    database: 8
    port: 6379
    password: HBQ521521cf*
    timeout: 3000ms
  servlet: #文件相关
    multipart:
      max-file-size: -1
      maxRequestSize: -1

#mybatis配置逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    call-setters-on-nulls: true   #配置返回结果集为空时仍返回字段

#输出日志位置
log:
  url: C:/logs/train

#minio文件服务
minio:
  endpoint: https://minio.service.cf/
  accessKey: admin
  secretKey: HBQ521521cf*
  bucketName: file